<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageVersion Include="Markdig" Version="1.2.0" />
		<PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
		<PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.1839" />
		<PackageVersion Include="Microsoft.WindowsAppSDK.Base" Version="2.0.4" />
		<PackageVersion Include="Microsoft.WindowsAppSDK.DWrite" Version="2.1.0" />
		<PackageVersion Include="Microsoft.WindowsAppSDK.Foundation" Version="2.0.21" />
		<PackageVersion Include="Microsoft.WindowsAppSDK.WinUI" Version="2.1.0" />
	</ItemGroup>
</Project>